version: 2.0.{build}
branches:
  except:
  - gh-pages
skip_tags: true
os: Visual Studio 2015
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- nuget restore
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: FPQi+Lo3oRi4ms08/OW8SPoW77VX8YDHUz9e2U+iikxz9gcH0t2Jk2wBGAODRFkw
  on:
    branch: master
- provider: GitHub
  auth_token:
    secure: QUNpmgp2dvA0M/Veuo7NJkjNXBJOxFsDAartHAjZfKhaLzFKdITHHhmST6ZUTdxu
  on:
    branch: master
